### PR TITLE
Added a comment on body in the bartik theme style.css

### PR DESCRIPTION
**Pull request by jfbuildstuff**
How does this look?

### CODE REVIEW

**Comment by swalkergibson** [comment]
You should never branch from master unless it is a hotfix for production.
All feature branches should emanate from develop.

**Comment by jfbuildstuff** [comment]
Yeah I F-ed that up. It's because I didn't pull down the develop or staging branches I think... When I pull the repo for the first time should I do 'git branch --all' or something like that?

**Comment by swalkergibson** [comment]
There are a couple of approaches. How did you originally get the repo? Did
you do a git clone?

**Comment by jfbuildstuff** [comment]
No I just did a 'git pull'

**Comment by swalkergibson** [comment]
Did you download the archive of the site from Github, then? I'm trying to
understand how you originally got the repo. Doing git pull from an
arbitrary directory on your local machine wouldn't do anything, lol.

**Comment by jfbuildstuff** [comment]
Yeah I did a pull request from in my local dev folder and it pulled all the files to my local machine. For reals. Never seen that before? LOL

**Comment by jfbuildstuff** [comment]
I set up a folder where my MAMP set up is pointed to, then did git remote add http://thingy , then git pull

**Comment by swalkergibson** [comment]
Oh, you didn't tell me you added the remote. Anyway, your terminology is a
little wonky. A pull request is a specific feature of Github the website,
not of git itself. You just pulled the remote branches, which does work.
However, when setting up the repo, you should use git clone instead of what
you just did so that you can also get all of the tags associated with the
repo, and all of the branch history.

**Pull request closed without merging**
